#!/bin/bash -e
# re-generate the edgegap client from the api declation
wget https://api.edgegap.com/swagger.json -O swagger.json
docker run \
	--rm -v $PWD:/local openapitools/openapi-generator-cli generate \
	-i /local/swagger.json -g rust -o /local/edgegap --additional-properties=supportAsync=false,library=reqwest,packageName=edgegap,packageVersion=0.1.0
rm swagger.json
# Autogenerated description field is too long for crates.io, tidy up the cargo file.
#  sed -i for in-place editing behaves differently on different OSes, so we use a temp file.
cd edgegap
cat Cargo.toml | \
	sed -e 's/^description =.*$/description = "Auto-generated client library for the Edgegap API, used by the arbctl tool"/' \
	    -e '/^description.*/a \
repository = "https://github.com/RJ/edgegap-arbctl/"' > Cargo.toml.publish \
	&& rm Cargo.toml && mv Cargo.toml.publish Cargo.toml
